services:
  banyandb:
    image: apache/skywalking-banyandb:latest
    container_name: banyandb
    command: standalone
    ports:
      - "17912:17912" # gRPC
      - "17913:17913" # HTTP (optional)
    networks:
      - skywalking-net

  oap:
    image: apache/skywalking-oap-server:10.2.0
    container_name: oap
    restart: always
    environment:
      SW_STORAGE: banyandb
      SW_STORAGE_BANYANDB_TARGETS: banyandb:17912
    depends_on:
      - banyandb
    ports:
      - "11800:11800" # gRPC for agents
      - "12800:12800" # HTTP REST API
    networks:
      - skywalking-net

  ui:
    image: apache/skywalking-ui:10.2.0
    container_name: skywalking-ui
    environment:
      SW_OAP_ADDRESS: http://oap:12800
    ports:
      - "8080:8080"
    depends_on:
      - oap
    networks:
      - skywalking-net

networks:
  skywalking-net:
    driver: bridge

