# See https://github.com/open-telemetry/opentelemetry-configuration for details on schema and examples

file_format: "1.0-rc.1"

resource:
  attributes:
    - name: service.name
      value: file-configuration-example

propagator:
  composite:
    - tracecontext:
    - baggage:

tracer_provider:
  processors:
    - batch:
        exporter:
          console:

meter_provider:
  readers:
    - periodic:
        exporter:
          console:
  views:
    - selector:
        instrument_type: histogram
      stream:
        aggregation:
          drop: